### ISSUE TITLE
Unable to open comic pages from thumbnail in web app

### ISSUE THREAD

**Issue by rapidswing** [coryo/ComicReader.bundle#9]
When using the Plex web app, clicking on a comic's thumbnail does nothing.  I've tried Chrome and Edge on Windows 10, as well as Chrome, Opera, and others on Android 7.1.2.

The pages open correctly from a thumbnail when using a native Plex app.  This worked for me with the UWP and Android apps.

Plex Media Server is version 3.9.1 on Ubuntu 16.04.02.

Attached is the browser's console output when clicking on a thumbnail.

[WebAppError.txt](https://github.com/coryo/ComicReader.bundle/files/1139765/WebAppError.txt)

**Comment by ghost** [comment]
Hello
I have the same issue.

**Comment by oboingo** [comment]
Me too.  I can see the thumbnails. In the web app when I click on them, nothing visible happens.  JS Console shows:

`main-0-99755cd0d68fb34ec303-plex-3.9.1-85417e0.js:2787 [Commands] Executing playMedia
main-0-99755cd0d68fb34ec303-plex-3.9.1-85417e0.js:2787 [Commands] Executing persistPlayQueue
main-0-99755cd0d68fb34ec303-plex-3.9.1-85417e0.js:922 Uncaught TypeError: Cannot read property 'length' of undefined
    at a (http://site:32400/web/js/main-0-99755cd0d68fb34ec303-plex-3.9.1-85417e0.js:922:306)
    at i (http://site:32400/web/js/main-0-99755cd0d68fb34ec303-plex-3.9.1-85417e0.js:3260:386)
    at Object.a [as startPlayback] (http://site:32400/web/js/main-0-99755cd0d68fb34ec303-plex-3.9.1-85417e0.js:3262:15)
    at Object.<anonymous> (http://site:32400/web/js/main-0-99755cd0d68fb34ec303-plex-3.9.1-85417e0.js:3298:366)
    at d (http://site:32400/web/js/vendors-1-05ee7eb11f0adf375042-plex-3.9.1-85417e0.js:576:70)
    at Object.add [as done] (http://site:32400/web/js/vendors-1-05ee7eb11f0adf375042-plex-3.9.1-85417e0.js:576:381)
    at n.i.a.(anonymous function) (http://site:32400/web/js/main-0-99755cd0d68fb34ec303-plex-3.9.1-85417e0.js:3298:324)
    at r (http://site:32400/web/js/main-0-99755cd0d68fb34ec303-plex-3.9.1-85417e0.js:2762:192)
    at Object.startPlayback (http://site:32400/web/js/main-0-99755cd0d68fb34ec303-plex-3.9.1-85417e0.js:7047:442)
    at t.componentWillMount (http://site:32400/web/js/main-0-99755cd0d68fb34ec303-plex-3.9.1-85417e0.js:4703:172)`

**Comment by cyberweasel** [comment]
i am unable to open the comics in any client.  Error says can't find unrar.  running on ubuntu.  unrar and p7zip installed and run from command line with from $PATH.  not sure what else I am missing.  Thanks.
